---
title: "TBD"
subtitle: "TBD"
author: "Bongju Yoo and Najma Osman"
thanks: "Code and data are available at: https://github.com/bonjwow/lost-wallet"
date: "`r format(Sys.time(), '%d %B %Y')`"
abstract: "First sentence. Second sentence. Third sentence. Fourth sentence."
output:
  bookdown::pdf_document2:
header-includes:
   - \usepackage{dcolumn} 
toc: FALSE
bibliography: references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggplot2)
library(ggalt)
library(ggthemes)
library(kableExtra)
library(janitor)
library(dplyr)
library(stargazer)

# install.packages ("gmodels")
library(gmodels)

# install.packages("pwr")
library(pwr)

### Import the cleaned data
dfCleanBehav <- readr::read_csv("../../inputs/data/clean_behavioral-data.csv")
dfBehavModel <- readr::read_csv("../../inputs/data/clean_behavioral-data_model.csv")
```

```{r, echo = FALSE, message = FALSE}
#### Define color HEX Code ####
colorRed <- "#E43B2D"
colorOrange <- "#F27E33"
colorBrown <- "#A65629"
colorGray <- "#E3E2E1"
```


# Introduction



# Data

```{r, echo = FALSE, message = FALSE}
### All wallets with no money
dfNoMoney <- 
  dfCleanBehav %>%
  filter(cond == 0) %>%
  group_by(country_2) %>%
  tally()

### All wallets with money
dfMoney <- 
  dfCleanBehav %>%
  filter(cond == 1) %>%
  group_by(country_2) %>%
  tally()

### Returned wallets with no money
dfReturnedNoMoney <-
  dfCleanBehav %>%
  filter(cond == 0 & response == 100) %>%
  group_by(country_2) %>%
  tally()

### Returned wallets with money
dfReturnedMoney <-
  dfCleanBehav %>%
  filter(cond == 1 & response == 100) %>%
  group_by(country_2) %>%
  tally()

### Merge all wallets and returned wallets with no money
dfMergedNoMoney <-
  merge(x = dfNoMoney, y = dfReturnedNoMoney, by = "country_2", all.x = TRUE) %>%
  mutate(rating = round(n.y / n.x * 100, 2)) %>%
  rename(country = "country_2") %>%
  rename(total = "n.x") %>%
  rename(returned = "n.y")

### Merge all wallets and returned wallets with money
dfMergedMoney <-
  merge(x = dfMoney, y = dfReturnedMoney, by = "country_2", all.x = TRUE) %>%
  mutate(rating = round(n.y / n.x * 100, 2)) %>%
  rename(country = "country_2") %>%
  rename(total = "n.x") %>%
  rename(returned = "n.y")
  
```


```{r, echo = FALSE, message = FALSE}

#### Dumbbell plot: Share of wallets reported by country ####

dfRatings <- 
  data.frame(country = dfMergedNoMoney$country,
             noMoney = dfMergedNoMoney$rating,
             money = dfMergedMoney$rating) %>%
  arrange(desc(noMoney))

### Reorder factor levels
dfRatings$country <- reorder(dfRatings$country, dfRatings$noMoney)

ggplot(dfRatings, aes(y = country, x = noMoney, xend = money)) +
  geom_dumbbell(size = 2, 
                color = colorGray,
                colour_x = colorOrange, 
                colour_xend = colorRed,
                dot_guide = TRUE, 
                dot_guide_size = 0.05,
                show.legend = TRUE) +
                # TODO: Fix legend 
  labs(x = NULL, y = NULL, title = "Share of wallets reported by country") +
  theme_minimal() +
  scale_color_manual(name = "", values = c("red", "blue")) +
  theme(panel.grid.major.x = element_line(size = 0.02))

```

```{r, echo = FALSE, message = FALSE}
#### Line chart: Reporting rates as a function of monetary stakes ####

### Report rate: Poland, UK, and USA
dfRateNoMoney <-
  dfMergedNoMoney %>%
  filter(country == "Poland" | country == "UK" | country == "USA")

dfRateMoney <-
  dfMergedMoney %>%
  filter(country == "Poland" | country == "UK" | country == "USA")
  
### All wallets with big money
dfBigMoney <- 
  dfCleanBehav %>%
  filter(cond == 2) %>%
  group_by(country_2) %>%
  tally()

### Returned wallets with big money
dfReturnedBigMoney <-
  dfCleanBehav %>%
  filter(cond == 2 & response == 100) %>%
  group_by(country_2) %>%
  tally()

### Merge all wallets and returned wallets with money
dfMergedBigMoney <-
  merge(x = dfBigMoney, y = dfReturnedBigMoney, by = "country_2", all.x = TRUE) %>%
  mutate(rating = round(n.y / n.x * 100, 2)) %>%
  rename(country = "country_2") %>%
  rename(total = "n.x") %>%
  rename(returned = "n.y")

### Bind all conditions
dfRateNoMoney["condition"] <- "NoMoney"
dfRateMoney["condition"] <- "Money"
dfMergedBigMoney["condition"] <- "BigMoney"
dfRate3Cond <- rbind(dfRateNoMoney, dfRateMoney, dfMergedBigMoney)

### Sort by condition
dfRate3Cond$condition <- factor(dfRate3Cond$condition, 
                                levels = c("NoMoney", "Money", "BigMoney"))

### Display data in a line graph
ggplot(data = dfRate3Cond,
       aes(x = condition,
           y = rating,
           group = country,
           color = country)) +
  geom_line(size = 1) +
  scale_color_manual(values = c(colorBrown, colorRed, colorOrange)) +
  geom_point(size = 3) +
  theme_bw() +
  theme(axis.line = element_line(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        panel.background = element_blank()) +
  xlab("") + 
  ylab("Reporting Rate(%)") 

```


## Description of Study

## Methodology and Data Collection

## Power Analysis
```{r, echo = FALSE, message = FALSE}
dfPwr <-
  dfBehavModel %>%
  select('cond',
         'response') %>%
  filter(cond == 0 | cond == 1)

CrossTable(dfPwr$cond, dfPwr$response, chisq=TRUE, format=c("SPSS"))
```


```{r, echo = FALSE, message = FALSE}
freqByCond <-
  dfBehavModel %>%
  select('cond',
         'response') %>%
  filter(cond == 0 | cond == 1) %>%
  group_by(cond, response) %>%
  summarise(n = n()) %>%
  mutate(freq = n / sum(n))

propNoMoneyReturned <- freqByCond$freq[2]
proMoneyReturned <- freqByCond$freq[4]

# Reference Code: https://cran.r-project.org/web/packages/pwr/pwr.pdf
effectSize <- 2 * asin(sqrt(proMoneyReturned)) - 2 * asin(sqrt(propNoMoneyReturned))

### Two-sample test for proportions (Unequal sample sizes)
# Reference Code:https://cran.r-project.org/web/packages/pwr/vignettes/pwr-vignette.html
# Reference: Conventional effect size from Cohen (1982)
pwr.2p.test(h = effectSize, sig.level = 0.05, power = 0.8)
```


# Model


# Results

```{r S8, echo = FALSE, message = FALSE, warning = FALSE, results = 'asis'}
### conditions
# 0 - no money, 1 - money, 2 - big money, 3 - money no key.

# controls:
  # fixed effects for institution and city
  # treatment condition
# binary controls:
  # male, above 40, coworkers, computer, bystanders

# code dummy variables
s8_model <- dfBehavModel %>%
  mutate(no_money = if_else(cond == 0, 1, 0)) %>%
  mutate(money = if_else(cond != 0, 1, 0)) 

# regression models
s8_main_result <- lm(response ~ cond, data = s8_model)
s8_money_result <- lm(response ~ cond + male + above40 + computer + coworkers + other_bystanders, data = s8_model)

# final table (S8)
stargazer(s8_main_result, s8_money_result, 
          title = "Reporting rates in the Money and No Money Condition", 
          header = FALSE,
          align = TRUE, 
          type = 'latex', 
          dep.var.labels = "Response", 
          covariate.labels = c("Money", "Male", "Above 40", "Computer", "Coworkers", "Other Bystanders", "Constant"))

```

```{r S9, echo = FALSE, warning = FALSE, message = FALSE, results = "asis"}
### conditions
# 0 - no money, 1 - money, 2 - big money, 3 - money no key.

# controls:
  # fixed effects for institution and city
  # treatment condition
# binary controls:
  # situation
  # recipient
  # other treatments

### conditions (money vs big money) - next step is creating dummy variables for big money + money to finalize the table

# UK, Poland, and US
s9_main <- dfBehavModel %>%
  filter(country == 39 | country == 27 | country == 40) %>%
  mutate(money = if_else(cond == 1, 1, 0)) %>%
  mutate(big_money = if_else(cond == 2, 1, 0))

s9_main_result <- lm(response ~ money + big_money, data = s9_main)

# UK
s9_uk <- s9_main %>%
  filter(country == 39)
s9_uk_result <- lm(response ~ money + big_money, data = s9_uk)

# Poland
s9_poland <- s9_main %>%
  filter(country == 27)
  
s9_poland_result <- lm(response ~ money + big_money, data = s9_poland)

# USA
s9_usa <- s9_main %>%
  filter(country == 40)
s9_usa_result <- lm(response ~ money + big_money, data = s9_usa)

# final table
stargazer(s9_main_result, s9_uk_result, s9_poland_result, s9_usa_result, 
          title = "Reporting rates in NoMoney, Money, and Big Money condition",
          header = FALSE,
          align = TRUE, 
          font.size = "small",
          type = 'latex', 
          dep.var.labels = "Response", 
          covariate.labels = c("Money", "Big Money", "Constant"),
          column.labels = c("UK, Poland, and US", "United Kingdom", "Poland", "United States"))
```

```{r S10, echo = FALSE, warning = FALSE, message = FALSE, results = "asis"}
### conditions
# 0 - no money, 1 - money, 2 - big money, 3 - money no key.

# controls:
  # fixed effects for institution and city
  # treatment condition
# binary controls:
  # situation
  # recipient
  # other treatments

### conditions (money vs big money) - next step is creating dummy variables for big money + money to finalize the table

# UK, Poland, and US
s10_main <- dfBehavModel %>%
  filter(country == 39 | country == 27 | country == 40)
s10_main$cond <- ifelse(s10_main$cond == 3, 1, 0)


s10_main_result <- lm(response ~ cond, data = s9_main)

# UK
s10_uk <- s9_main %>%
  filter(country == 39)
s10_uk_result <- lm(response ~ cond, data = s10_uk)

# Poland
s10_poland <- s10_main %>%
  filter(country == 27)
  
s10_poland_result <- lm(response ~ cond, data = s10_poland)

# USA
s10_usa <- s10_main %>%
  filter(country == 40)
s10_usa_result <- lm(response ~ cond, data = s10_usa)

# final table
stargazer(s10_main_result, s10_uk_result, s10_poland_result, s10_usa_result, 
          title = "Reporting rates in Money-No Key condition", 
          header = FALSE,
          align = TRUE, 
          font.size = "small",
          type = 'latex', 
          dep.var.labels = "Response", 
          covariate.labels = c("Money-NoKey", "Constant"),
          column.labels = c("UK, Poland, and US", "United Kingdom", "Poland", "United States"))
```

\newpage 

# Discussion

## Overview of Findings

## Weaknesses and next steps

Weaknesses and next steps should also be included.

\newpage

# Appendix {-}

\newpage


# References


